/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NamedObject', 'model/Relation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./NamedObject'), require('./Relation'));
  } else {
    // Browser globals (root is window)
    if (!root.BioLinkApi) {
      root.BioLinkApi = {};
    }
    root.BioLinkApi.AnnotationExtension = factory(root.BioLinkApi.ApiClient, root.BioLinkApi.NamedObject, root.BioLinkApi.Relation);
  }
}(this, function(ApiClient, NamedObject, Relation) {
  'use strict';




  /**
   * The AnnotationExtension model module.
   * @module model/AnnotationExtension
   * @version 0.1
   */

  /**
   * Constructs a new <code>AnnotationExtension</code>.
   * @alias module:model/AnnotationExtension
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>AnnotationExtension</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnnotationExtension} obj Optional instance to populate.
   * @return {module:model/AnnotationExtension} The populated <code>AnnotationExtension</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('filler')) {
        obj['filler'] = NamedObject.constructFromObject(data['filler']);
      }
      if (data.hasOwnProperty('relation_chain')) {
        obj['relation_chain'] = ApiClient.convertToType(data['relation_chain'], [Relation]);
      }
    }
    return obj;
  }

  /**
   * Extension interpreted as OWL expression (r1 some r2 some .. some filler).
   * @member {module:model/NamedObject} filler
   */
  exports.prototype['filler'] = undefined;
  /**
   * Relationship type. If more than one value, interpreted as chain
   * @member {Array.<module:model/Relation>} relation_chain
   */
  exports.prototype['relation_chain'] = undefined;



  return exports;
}));


