/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Association', 'model/BioObject', 'model/Seq', 'model/SequenceLocation', 'model/Taxon'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Association'), require('./BioObject'), require('./Seq'), require('./SequenceLocation'), require('./Taxon'));
  } else {
    // Browser globals (root is window)
    if (!root.BioLinkApi) {
      root.BioLinkApi = {};
    }
    root.BioLinkApi.SequenceFeature = factory(root.BioLinkApi.ApiClient, root.BioLinkApi.Association, root.BioLinkApi.BioObject, root.BioLinkApi.Seq, root.BioLinkApi.SequenceLocation, root.BioLinkApi.Taxon);
  }
}(this, function(ApiClient, Association, BioObject, Seq, SequenceLocation, Taxon) {
  'use strict';




  /**
   * The SequenceFeature model module.
   * @module model/SequenceFeature
   * @version 0.1
   */

  /**
   * Constructs a new <code>SequenceFeature</code>.
   * @alias module:model/SequenceFeature
   * @class
   * @implements module:model/BioObject
   */
  var exports = function() {
    var _this = this;

    BioObject.call(_this);



  };

  /**
   * Constructs a <code>SequenceFeature</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SequenceFeature} obj Optional instance to populate.
   * @return {module:model/SequenceFeature} The populated <code>SequenceFeature</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      BioObject.constructFromObject(data, obj);
      if (data.hasOwnProperty('locations')) {
        obj['locations'] = ApiClient.convertToType(data['locations'], [SequenceLocation]);
      }
      if (data.hasOwnProperty('homology_associations')) {
        obj['homology_associations'] = ApiClient.convertToType(data['homology_associations'], [Association]);
      }
      if (data.hasOwnProperty('seq')) {
        obj['seq'] = Seq.constructFromObject(data['seq']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/SequenceLocation>} locations
   */
  exports.prototype['locations'] = undefined;
  /**
   * @member {Array.<module:model/Association>} homology_associations
   */
  exports.prototype['homology_associations'] = undefined;
  /**
   * @member {module:model/Seq} seq
   */
  exports.prototype['seq'] = undefined;

  // Implement BioObject interface:
  /**
   * RDFS Label
   * @member {String} label
   */
exports.prototype['label'] = undefined;

  /**
   * ID or CURIE e.g. MGI:1201606
   * @member {String} id
   */
exports.prototype['id'] = undefined;

  /**
   * @member {Array.<String>} categories
   */
exports.prototype['categories'] = undefined;

  /**
   * Database cross-references. These are usually CURIEs, but may also be URLs. E.g. ENSEMBL:ENSG00000099940 
   * @member {Array.<String>} xrefs
   */
exports.prototype['xrefs'] = undefined;

  /**
   * Taxon to which the object belongs
   * @member {module:model/Taxon} taxon
   */
exports.prototype['taxon'] = undefined;



  return exports;
}));


