/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BioLinkApi) {
      root.BioLinkApi = {};
    }
    root.BioLinkApi.VariantSet = factory(root.BioLinkApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The VariantSet model module.
   * @module model/VariantSet
   * @version 0.1
   */

  /**
   * Constructs a new <code>VariantSet</code>.
   * @alias module:model/VariantSet
   * @class
   * @param body {String} Article content
   * @param title {String} Article title
   */
  var exports = function(body, title) {
    var _this = this;

    _this['body'] = body;
    _this['title'] = title;




  };

  /**
   * Constructs a <code>VariantSet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VariantSet} obj Optional instance to populate.
   * @return {module:model/VariantSet} The populated <code>VariantSet</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('body')) {
        obj['body'] = ApiClient.convertToType(data['body'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('category_id')) {
        obj['category_id'] = ApiClient.convertToType(data['category_id'], 'Integer');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('pub_date')) {
        obj['pub_date'] = ApiClient.convertToType(data['pub_date'], 'Date');
      }
      if (data.hasOwnProperty('category')) {
        obj['category'] = ApiClient.convertToType(data['category'], 'String');
      }
    }
    return obj;
  }

  /**
   * Article content
   * @member {String} body
   */
  exports.prototype['body'] = undefined;
  /**
   * Article title
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {Integer} category_id
   */
  exports.prototype['category_id'] = undefined;
  /**
   * The unique identifier of a variant set
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Date} pub_date
   */
  exports.prototype['pub_date'] = undefined;
  /**
   * @member {String} category
   */
  exports.prototype['category'] = undefined;



  return exports;
}));


