/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CompactAssociationSet'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/CompactAssociationSet'));
  } else {
    // Browser globals (root is window)
    if (!root.BioLinkApi) {
      root.BioLinkApi = {};
    }
    root.BioLinkApi.BioentitysethomologsApi = factory(root.BioLinkApi.ApiClient, root.BioLinkApi.CompactAssociationSet);
  }
}(this, function(ApiClient, CompactAssociationSet) {
  'use strict';

  /**
   * Bioentitysethomologs service.
   * @module api/BioentitysethomologsApi
   * @version 0.1
   */

  /**
   * Constructs a new BioentitysethomologsApi. 
   * @alias module:api/BioentitysethomologsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getEntitySetHomologs operation.
     * @callback module:api/BioentitysethomologsApi~getEntitySetHomologsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CompactAssociationSet>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns homology associations for a given input set of genes
     * @param {Object} opts Optional parameters
     * @param {Array.<String>} opts.subject Entity ids to be examined, e.g. NCBIGene:9342, NCBIGene:7227, NCBIGene:8131, NCBIGene:157570, NCBIGene:51164, NCBIGene:6689, NCBIGene:6387
     * @param {module:api/BioentitysethomologsApi~getEntitySetHomologsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {Array.<module:model/CompactAssociationSet>}
     */
    this.getEntitySetHomologs = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'subject': this.apiClient.buildCollectionParam(opts['subject'], 'multi')
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [CompactAssociationSet];

      return this.apiClient.callApi(
        '/bioentityset/homologs/homologs/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
