/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Graph'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Graph'));
  } else {
    // Browser globals (root is window)
    if (!root.BioLinkApi) {
      root.BioLinkApi = {};
    }
    root.BioLinkApi.EvidencegraphApi = factory(root.BioLinkApi.ApiClient, root.BioLinkApi.Graph);
  }
}(this, function(ApiClient, Graph) {
  'use strict';

  /**
   * Evidencegraph service.
   * @module api/EvidencegraphApi
   * @version 0.1
   */

  /**
   * Constructs a new EvidencegraphApi. 
   * @alias module:api/EvidencegraphApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getAssociationObject operation.
     * @callback module:api/EvidencegraphApi~getAssociationObjectCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Graph>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns evidence graph object for a given association
     * Note that every association is assumed to have a unique ID
     * @param {String} id association id, e.g. cfef92b7-bfa3-44c2-a537-579078d2de37
     * @param {module:api/EvidencegraphApi~getAssociationObjectCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {Array.<module:model/Graph>}
     */
    this.getAssociationObject = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling getAssociationObject";
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Graph];

      return this.apiClient.callApi(
        '/evidence/graph/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAssociationObject_0 operation.
     * @callback module:api/EvidencegraphApi~getAssociationObject_0Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns evidence graph as a png
     * TODO - requires matplotlib which is hard to install
     * @param {String} id association id, e.g. cfef92b7-bfa3-44c2-a537-579078d2de37
     * @param {module:api/EvidencegraphApi~getAssociationObject_0Callback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getAssociationObject_0 = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling getAssociationObject_0";
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/evidence/graph/{id}/image', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
