/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SequenceFeature'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/SequenceFeature'));
  } else {
    // Browser globals (root is window)
    if (!root.BioLinkApi) {
      root.BioLinkApi = {};
    }
    root.BioLinkApi.GenomefeaturesApi = factory(root.BioLinkApi.ApiClient, root.BioLinkApi.SequenceFeature);
  }
}(this, function(ApiClient, SequenceFeature) {
  'use strict';

  /**
   * Genomefeatures service.
   * @module api/GenomefeaturesApi
   * @version 0.1
   */

  /**
   * Constructs a new GenomefeaturesApi. 
   * @alias module:api/GenomefeaturesApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getFeaturesWithinResource operation.
     * @callback module:api/GenomefeaturesApi~getFeaturesWithinResourceCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/SequenceFeature>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns list of matches
     * @param {String} begin 
     * @param {String} end 
     * @param {String} build 
     * @param {String} reference 
     * @param {module:api/GenomefeaturesApi~getFeaturesWithinResourceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {Array.<module:model/SequenceFeature>}
     */
    this.getFeaturesWithinResource = function(begin, end, build, reference, callback) {
      var postBody = null;

      // verify the required parameter 'begin' is set
      if (begin == undefined || begin == null) {
        throw "Missing the required parameter 'begin' when calling getFeaturesWithinResource";
      }

      // verify the required parameter 'end' is set
      if (end == undefined || end == null) {
        throw "Missing the required parameter 'end' when calling getFeaturesWithinResource";
      }

      // verify the required parameter 'build' is set
      if (build == undefined || build == null) {
        throw "Missing the required parameter 'build' when calling getFeaturesWithinResource";
      }

      // verify the required parameter 'reference' is set
      if (reference == undefined || reference == null) {
        throw "Missing the required parameter 'reference' when calling getFeaturesWithinResource";
      }


      var pathParams = {
        'begin': begin,
        'end': end,
        'build': build,
        'reference': reference
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [SequenceFeature];

      return this.apiClient.callApi(
        '/genome/features/within/{build}/{reference}/{begin}/{end}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
