/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BioLinkApi) {
      root.BioLinkApi = {};
    }
    root.BioLinkApi.IdentifierprefixesApi = factory(root.BioLinkApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * Identifierprefixes service.
   * @module api/IdentifierprefixesApi
   * @version 0.1
   */

  /**
   * Constructs a new IdentifierprefixesApi. 
   * @alias module:api/IdentifierprefixesApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getPrefixCollection operation.
     * @callback module:api/IdentifierprefixesApi~getPrefixCollectionCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns list of prefixes
     * @param {module:api/IdentifierprefixesApi~getPrefixCollectionCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getPrefixCollection = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/identifier/prefixes/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getPrefixCollection_0 operation.
     * @callback module:api/IdentifierprefixesApi~getPrefixCollection_0Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns contracted URI
     * @param {String} uri URI of entity to be contracted to identifier/CURIE, e.g \&quot;http://www.informatics.jax.org/accession/MGI:1\&quot;
     * @param {module:api/IdentifierprefixesApi~getPrefixCollection_0Callback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getPrefixCollection_0 = function(uri, callback) {
      var postBody = null;

      // verify the required parameter 'uri' is set
      if (uri == undefined || uri == null) {
        throw "Missing the required parameter 'uri' when calling getPrefixCollection_0";
      }


      var pathParams = {
        'uri': uri
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/identifier/prefixes/contract/{uri}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getPrefixCollection_1 operation.
     * @callback module:api/IdentifierprefixesApi~getPrefixCollection_1Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns expanded URI
     * @param {String} id ID of entity to be contracted to URI, e.g \&quot;MGI:1\&quot;
     * @param {module:api/IdentifierprefixesApi~getPrefixCollection_1Callback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getPrefixCollection_1 = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling getPrefixCollection_1";
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/identifier/prefixes/expand/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
