/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BioLinkApi) {
      root.BioLinkApi = {};
    }
    root.BioLinkApi.OntolApi = factory(root.BioLinkApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * Ontol service.
   * @module api/OntolApi
   * @version 0.1
   */

  /**
   * Constructs a new OntolApi. 
   * @alias module:api/OntolApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getInformationContentResource operation.
     * @callback module:api/OntolApi~getInformationContentResourceCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Calculates information content
     * @param {String} objectCategory 
     * @param {String} subjectTaxon 
     * @param {String} subjectCategory 
     * @param {Object} opts Optional parameters
     * @param {String} opts.evidence Object id, e.g. ECO:0000501 (for IEA; Includes inferred by default)                     or a specific publication or other supporting ibject, e.g. ZFIN:ZDB-PUB-060503-2.                     
     * @param {module:api/OntolApi~getInformationContentResourceCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getInformationContentResource = function(objectCategory, subjectTaxon, subjectCategory, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'objectCategory' is set
      if (objectCategory == undefined || objectCategory == null) {
        throw "Missing the required parameter 'objectCategory' when calling getInformationContentResource";
      }

      // verify the required parameter 'subjectTaxon' is set
      if (subjectTaxon == undefined || subjectTaxon == null) {
        throw "Missing the required parameter 'subjectTaxon' when calling getInformationContentResource";
      }

      // verify the required parameter 'subjectCategory' is set
      if (subjectCategory == undefined || subjectCategory == null) {
        throw "Missing the required parameter 'subjectCategory' when calling getInformationContentResource";
      }


      var pathParams = {
        'object_category': objectCategory,
        'subject_taxon': subjectTaxon,
        'subject_category': subjectCategory
      };
      var queryParams = {
        'evidence': opts['evidence']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/ontol/information_content/{subject_category}/{object_category}/{subject_taxon}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
