/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BioLinkApi) {
      root.BioLinkApi = {};
    }
    root.BioLinkApi.PairsimApi = factory(root.BioLinkApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * Pairsim service.
   * @module api/PairsimApi
   * @version 0.1
   */

  /**
   * Constructs a new PairsimApi. 
   * @alias module:api/PairsimApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getPairSimJaccardResource operation.
     * @callback module:api/PairsimApi~getPairSimJaccardResourceCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get pairwise similarity
     * @param {String} id2 id, e.g. NCBIGene:1200; ZFIN:ZDB-GENE-980528-2059; UniProtKB:P12644
     * @param {String} id1 id, e.g. NCBIGene:10891; ZFIN:ZDB-GENE-980526-166; UniProtKB:Q15465
     * @param {Object} opts Optional parameters
     * @param {String} opts.objectCategory e.g. disease, phenotype, gene. Two subjects will be compared based on overlap between associations to objects in this category
     * @param {module:api/PairsimApi~getPairSimJaccardResourceCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getPairSimJaccardResource = function(id2, id1, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id2' is set
      if (id2 == undefined || id2 == null) {
        throw "Missing the required parameter 'id2' when calling getPairSimJaccardResource";
      }

      // verify the required parameter 'id1' is set
      if (id1 == undefined || id1 == null) {
        throw "Missing the required parameter 'id1' when calling getPairSimJaccardResource";
      }


      var pathParams = {
        'id2': id2,
        'id1': id1
      };
      var queryParams = {
        'object_category': opts['objectCategory']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/pair/sim/jaccard/{id1}/{id2}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
