/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Association'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Association'));
  } else {
    // Browser globals (root is window)
    if (!root.BioLinkApi) {
      root.BioLinkApi = {};
    }
    root.BioLinkApi.SearchentityApi = factory(root.BioLinkApi.ApiClient, root.BioLinkApi.Association);
  }
}(this, function(ApiClient, Association) {
  'use strict';

  /**
   * Searchentity service.
   * @module api/SearchentityApi
   * @version 0.1
   */

  /**
   * Constructs a new SearchentityApi. 
   * @alias module:api/SearchentityApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getAuthocomplete operation.
     * @callback module:api/SearchentityApi~getAuthocompleteCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Association>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns list of matches
     * @param {String} term 
     * @param {Object} opts Optional parameters
     * @param {Array.<String>} opts.weightedAttribute weighted attributes, specified as a range from 0 to 1 plus an ontology term, e.g. 0.3*HP:0000001
     * @param {Array.<String>} opts.attribute positive attributes, e.g. ontology terms, to include in query
     * @param {Boolean} opts.noise If set, uses noise-tolerant querying, e.g owlsim, boqa
     * @param {String} opts.subjectTaxon SUBJECT TAXON id, e.g. NCBITaxon:9606. Includes inferred by default
     * @param {Array.<String>} opts.negativeAttribute negative attributes, e.g. ontology terms, to exclude in query
     * @param {module:api/SearchentityApi~getAuthocompleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {Array.<module:model/Association>}
     */
    this.getAuthocomplete = function(term, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'term' is set
      if (term == undefined || term == null) {
        throw "Missing the required parameter 'term' when calling getAuthocomplete";
      }


      var pathParams = {
        'term': term
      };
      var queryParams = {
        'weighted_attribute': this.apiClient.buildCollectionParam(opts['weightedAttribute'], 'multi'),
        'attribute': this.apiClient.buildCollectionParam(opts['attribute'], 'multi'),
        'noise': opts['noise'],
        'subject_taxon': opts['subjectTaxon'],
        'negative_attribute': this.apiClient.buildCollectionParam(opts['negativeAttribute'], 'multi')
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Association];

      return this.apiClient.callApi(
        '/search/entity/autocomplete/{term}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAuthocomplete_0 operation.
     * @callback module:api/SearchentityApi~getAuthocomplete_0Callback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Association>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns list of matches
     * @param {Object} opts Optional parameters
     * @param {Array.<String>} opts.weightedAttribute weighted attributes, specified as a range from 0 to 1 plus an ontology term, e.g. 0.3*HP:0000001
     * @param {Array.<String>} opts.attribute positive attributes, e.g. ontology terms, to include in query
     * @param {Boolean} opts.noise If set, uses noise-tolerant querying, e.g owlsim, boqa
     * @param {String} opts.subjectTaxon SUBJECT TAXON id, e.g. NCBITaxon:9606. Includes inferred by default
     * @param {Array.<String>} opts.negativeAttribute negative attributes, e.g. ontology terms, to exclude in query
     * @param {module:api/SearchentityApi~getAuthocomplete_0Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {Array.<module:model/Association>}
     */
    this.getAuthocomplete_0 = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'weighted_attribute': this.apiClient.buildCollectionParam(opts['weightedAttribute'], 'multi'),
        'attribute': this.apiClient.buildCollectionParam(opts['attribute'], 'multi'),
        'noise': opts['noise'],
        'subject_taxon': opts['subjectTaxon'],
        'negative_attribute': this.apiClient.buildCollectionParam(opts['negativeAttribute'], 'multi')
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Association];

      return this.apiClient.callApi(
        '/search/entity/query/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getSearchEntities operation.
     * @callback module:api/SearchentityApi~getSearchEntitiesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Association>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns list of matches
     * @param {String} term 
     * @param {Object} opts Optional parameters
     * @param {Array.<String>} opts.weightedAttribute weighted attributes, specified as a range from 0 to 1 plus an ontology term, e.g. 0.3*HP:0000001
     * @param {Array.<String>} opts.attribute positive attributes, e.g. ontology terms, to include in query
     * @param {Boolean} opts.noise If set, uses noise-tolerant querying, e.g owlsim, boqa
     * @param {String} opts.subjectTaxon SUBJECT TAXON id, e.g. NCBITaxon:9606. Includes inferred by default
     * @param {Array.<String>} opts.negativeAttribute negative attributes, e.g. ontology terms, to exclude in query
     * @param {module:api/SearchentityApi~getSearchEntitiesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {Array.<module:model/Association>}
     */
    this.getSearchEntities = function(term, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'term' is set
      if (term == undefined || term == null) {
        throw "Missing the required parameter 'term' when calling getSearchEntities";
      }


      var pathParams = {
        'term': term
      };
      var queryParams = {
        'weighted_attribute': this.apiClient.buildCollectionParam(opts['weightedAttribute'], 'multi'),
        'attribute': this.apiClient.buildCollectionParam(opts['attribute'], 'multi'),
        'noise': opts['noise'],
        'subject_taxon': opts['subjectTaxon'],
        'negative_attribute': this.apiClient.buildCollectionParam(opts['negativeAttribute'], 'multi')
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Association];

      return this.apiClient.callApi(
        '/search/entity/{term}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
