/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BioLinkApi);
  }
}(this, function(expect, BioLinkApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BioLinkApi.Association();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Association', function() {
    it('should create an instance of Association', function() {
      // uncomment below and update the code to test Association
      //var instane = new BioLinkApi.Association();
      //expect(instance).to.be.a(BioLinkApi.Association);
    });

    it('should have the property evidenceTypes (base name: "evidence_types")', function() {
      // uncomment below and update the code to test the property evidenceTypes
      //var instane = new BioLinkApi.Association();
      //expect(instance).to.be();
    });

    it('should have the property evidenceGraph (base name: "evidence_graph")', function() {
      // uncomment below and update the code to test the property evidenceGraph
      //var instane = new BioLinkApi.Association();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new BioLinkApi.Association();
      //expect(instance).to.be();
    });

    it('should have the property relation (base name: "relation")', function() {
      // uncomment below and update the code to test the property relation
      //var instane = new BioLinkApi.Association();
      //expect(instance).to.be();
    });

    it('should have the property providedBy (base name: "provided_by")', function() {
      // uncomment below and update the code to test the property providedBy
      //var instane = new BioLinkApi.Association();
      //expect(instance).to.be();
    });

    it('should have the property publications (base name: "publications")', function() {
      // uncomment below and update the code to test the property publications
      //var instane = new BioLinkApi.Association();
      //expect(instance).to.be();
    });

    it('should have the property objectExtension (base name: "object_extension")', function() {
      // uncomment below and update the code to test the property objectExtension
      //var instane = new BioLinkApi.Association();
      //expect(instance).to.be();
    });

    it('should have the property qualifiers (base name: "qualifiers")', function() {
      // uncomment below and update the code to test the property qualifiers
      //var instane = new BioLinkApi.Association();
      //expect(instance).to.be();
    });

    it('should have the property _object (base name: "object")', function() {
      // uncomment below and update the code to test the property _object
      //var instane = new BioLinkApi.Association();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instane = new BioLinkApi.Association();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new BioLinkApi.Association();
      //expect(instance).to.be();
    });

    it('should have the property subjectExtension (base name: "subject_extension")', function() {
      // uncomment below and update the code to test the property subjectExtension
      //var instane = new BioLinkApi.Association();
      //expect(instance).to.be();
    });

  });

}));
