/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BioLinkApi);
  }
}(this, function(expect, BioLinkApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BioLinkApi.Gene();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Gene', function() {
    it('should create an instance of Gene', function() {
      // uncomment below and update the code to test Gene
      //var instane = new BioLinkApi.Gene();
      //expect(instance).to.be.a(BioLinkApi.Gene);
    });

    it('should have the property pathwayAssociations (base name: "pathway_associations")', function() {
      // uncomment below and update the code to test the property pathwayAssociations
      //var instane = new BioLinkApi.Gene();
      //expect(instance).to.be();
    });

    it('should have the property genotypeAssociations (base name: "genotype_associations")', function() {
      // uncomment below and update the code to test the property genotypeAssociations
      //var instane = new BioLinkApi.Gene();
      //expect(instance).to.be();
    });

    it('should have the property fullName (base name: "full_name")', function() {
      // uncomment below and update the code to test the property fullName
      //var instane = new BioLinkApi.Gene();
      //expect(instance).to.be();
    });

    it('should have the property sequenceFeatures (base name: "sequence_features")', function() {
      // uncomment below and update the code to test the property sequenceFeatures
      //var instane = new BioLinkApi.Gene();
      //expect(instance).to.be();
    });

    it('should have the property functionAssociations (base name: "function_associations")', function() {
      // uncomment below and update the code to test the property functionAssociations
      //var instane = new BioLinkApi.Gene();
      //expect(instance).to.be();
    });

    it('should have the property interactionAssociations (base name: "interaction_associations")', function() {
      // uncomment below and update the code to test the property interactionAssociations
      //var instane = new BioLinkApi.Gene();
      //expect(instance).to.be();
    });

    it('should have the property transcripts (base name: "transcripts")', function() {
      // uncomment below and update the code to test the property transcripts
      //var instane = new BioLinkApi.Gene();
      //expect(instance).to.be();
    });

    it('should have the property literatureAssociations (base name: "literature_associations")', function() {
      // uncomment below and update the code to test the property literatureAssociations
      //var instane = new BioLinkApi.Gene();
      //expect(instance).to.be();
    });

    it('should have the property summaries (base name: "summaries")', function() {
      // uncomment below and update the code to test the property summaries
      //var instane = new BioLinkApi.Gene();
      //expect(instance).to.be();
    });

    it('should have the property chromosome (base name: "chromosome")', function() {
      // uncomment below and update the code to test the property chromosome
      //var instane = new BioLinkApi.Gene();
      //expect(instance).to.be();
    });

    it('should have the property diseaseAssociations (base name: "disease_associations")', function() {
      // uncomment below and update the code to test the property diseaseAssociations
      //var instane = new BioLinkApi.Gene();
      //expect(instance).to.be();
    });

    it('should have the property phenotypeAssociations (base name: "phenotype_associations")', function() {
      // uncomment below and update the code to test the property phenotypeAssociations
      //var instane = new BioLinkApi.Gene();
      //expect(instance).to.be();
    });

    it('should have the property homologyAssociations (base name: "homology_associations")', function() {
      // uncomment below and update the code to test the property homologyAssociations
      //var instane = new BioLinkApi.Gene();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new BioLinkApi.Gene();
      //expect(instance).to.be();
    });

    it('should have the property systematicName (base name: "systematic_name")', function() {
      // uncomment below and update the code to test the property systematicName
      //var instane = new BioLinkApi.Gene();
      //expect(instance).to.be();
    });

    it('should have the property families (base name: "families")', function() {
      // uncomment below and update the code to test the property families
      //var instane = new BioLinkApi.Gene();
      //expect(instance).to.be();
    });

  });

}));
