/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BioLinkApi);
  }
}(this, function(expect, BioLinkApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BioLinkApi.Genotype();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Genotype', function() {
    it('should create an instance of Genotype', function() {
      // uncomment below and update the code to test Genotype
      //var instane = new BioLinkApi.Genotype();
      //expect(instance).to.be.a(BioLinkApi.Genotype);
    });

    it('should have the property variantAssociations (base name: "variant_associations")', function() {
      // uncomment below and update the code to test the property variantAssociations
      //var instane = new BioLinkApi.Genotype();
      //expect(instance).to.be();
    });

    it('should have the property geneAssociations (base name: "gene_associations")', function() {
      // uncomment below and update the code to test the property geneAssociations
      //var instane = new BioLinkApi.Genotype();
      //expect(instance).to.be();
    });

    it('should have the property phenotypeAssociations (base name: "phenotype_associations")', function() {
      // uncomment below and update the code to test the property phenotypeAssociations
      //var instane = new BioLinkApi.Genotype();
      //expect(instance).to.be();
    });

    it('should have the property diseaseAssociations (base name: "disease_associations")', function() {
      // uncomment below and update the code to test the property diseaseAssociations
      //var instane = new BioLinkApi.Genotype();
      //expect(instance).to.be();
    });

  });

}));
