/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BioLinkApi);
  }
}(this, function(expect, BioLinkApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BioLinkApi.AssociationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AssociationApi', function() {
    describe('getAssociationObject', function() {
      it('should call getAssociationObject successfully', function(done) {
        //uncomment below and update the code to test getAssociationObject
        //instance.getAssociationObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssociationSearch', function() {
      it('should call getAssociationSearch successfully', function(done) {
        //uncomment below and update the code to test getAssociationSearch
        //instance.getAssociationSearch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssociationSearch_0', function() {
      it('should call getAssociationSearch_0 successfully', function(done) {
        //uncomment below and update the code to test getAssociationSearch_0
        //instance.getAssociationSearch_0(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssociationSearch_1', function() {
      it('should call getAssociationSearch_1 successfully', function(done) {
        //uncomment below and update the code to test getAssociationSearch_1
        //instance.getAssociationSearch_1(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssociationsFrom', function() {
      it('should call getAssociationsFrom successfully', function(done) {
        //uncomment below and update the code to test getAssociationsFrom
        //instance.getAssociationsFrom(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssociationsFrom_0', function() {
      it('should call getAssociationsFrom_0 successfully', function(done) {
        //uncomment below and update the code to test getAssociationsFrom_0
        //instance.getAssociationsFrom_0(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssociationsTo', function() {
      it('should call getAssociationsTo successfully', function(done) {
        //uncomment below and update the code to test getAssociationsTo
        //instance.getAssociationsTo(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
