/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BioLinkApi);
  }
}(this, function(expect, BioLinkApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BioLinkApi.BioentityApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BioentityApi', function() {
    describe('getAlleleObject', function() {
      it('should call getAlleleObject successfully', function(done) {
        //uncomment below and update the code to test getAlleleObject
        //instance.getAlleleObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAnatomyGeneAssociations', function() {
      it('should call getAnatomyGeneAssociations successfully', function(done) {
        //uncomment below and update the code to test getAnatomyGeneAssociations
        //instance.getAnatomyGeneAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAnatomyObject', function() {
      it('should call getAnatomyObject successfully', function(done) {
        //uncomment below and update the code to test getAnatomyObject
        //instance.getAnatomyObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAnatomyPhenotypeAssociations', function() {
      it('should call getAnatomyPhenotypeAssociations successfully', function(done) {
        //uncomment below and update the code to test getAnatomyPhenotypeAssociations
        //instance.getAnatomyPhenotypeAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDiseaseAnatomyAssociations', function() {
      it('should call getDiseaseAnatomyAssociations successfully', function(done) {
        //uncomment below and update the code to test getDiseaseAnatomyAssociations
        //instance.getDiseaseAnatomyAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDiseaseFunctionAssociations', function() {
      it('should call getDiseaseFunctionAssociations successfully', function(done) {
        //uncomment below and update the code to test getDiseaseFunctionAssociations
        //instance.getDiseaseFunctionAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDiseaseGeneAssociations', function() {
      it('should call getDiseaseGeneAssociations successfully', function(done) {
        //uncomment below and update the code to test getDiseaseGeneAssociations
        //instance.getDiseaseGeneAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDiseaseModelAssociations', function() {
      it('should call getDiseaseModelAssociations successfully', function(done) {
        //uncomment below and update the code to test getDiseaseModelAssociations
        //instance.getDiseaseModelAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDiseaseModelTaxonAssociations', function() {
      it('should call getDiseaseModelTaxonAssociations successfully', function(done) {
        //uncomment below and update the code to test getDiseaseModelTaxonAssociations
        //instance.getDiseaseModelTaxonAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDiseaseObject', function() {
      it('should call getDiseaseObject successfully', function(done) {
        //uncomment below and update the code to test getDiseaseObject
        //instance.getDiseaseObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDiseasePhenotypeAssociations', function() {
      it('should call getDiseasePhenotypeAssociations successfully', function(done) {
        //uncomment below and update the code to test getDiseasePhenotypeAssociations
        //instance.getDiseasePhenotypeAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDiseaseSubstanceAssociations', function() {
      it('should call getDiseaseSubstanceAssociations successfully', function(done) {
        //uncomment below and update the code to test getDiseaseSubstanceAssociations
        //instance.getDiseaseSubstanceAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDiseaseSubstanceAssociations_0', function() {
      it('should call getDiseaseSubstanceAssociations_0 successfully', function(done) {
        //uncomment below and update the code to test getDiseaseSubstanceAssociations_0
        //instance.getDiseaseSubstanceAssociations_0(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEnvironmentObject', function() {
      it('should call getEnvironmentObject successfully', function(done) {
        //uncomment below and update the code to test getEnvironmentObject
        //instance.getEnvironmentObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEnvironmentPhenotypeAssociations', function() {
      it('should call getEnvironmentPhenotypeAssociations successfully', function(done) {
        //uncomment below and update the code to test getEnvironmentPhenotypeAssociations
        //instance.getEnvironmentPhenotypeAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGeneExpressionAssociations', function() {
      it('should call getGeneExpressionAssociations successfully', function(done) {
        //uncomment below and update the code to test getGeneExpressionAssociations
        //instance.getGeneExpressionAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGeneFunctionAssociations', function() {
      it('should call getGeneFunctionAssociations successfully', function(done) {
        //uncomment below and update the code to test getGeneFunctionAssociations
        //instance.getGeneFunctionAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGeneHomologAssociations', function() {
      it('should call getGeneHomologAssociations successfully', function(done) {
        //uncomment below and update the code to test getGeneHomologAssociations
        //instance.getGeneHomologAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGeneInteractions', function() {
      it('should call getGeneInteractions successfully', function(done) {
        //uncomment below and update the code to test getGeneInteractions
        //instance.getGeneInteractions(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGeneObject', function() {
      it('should call getGeneObject successfully', function(done) {
        //uncomment below and update the code to test getGeneObject
        //instance.getGeneObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGenePhenotypeAssociations', function() {
      it('should call getGenePhenotypeAssociations successfully', function(done) {
        //uncomment below and update the code to test getGenePhenotypeAssociations
        //instance.getGenePhenotypeAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGenePublicationList', function() {
      it('should call getGenePublicationList successfully', function(done) {
        //uncomment below and update the code to test getGenePublicationList
        //instance.getGenePublicationList(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGeneproductObject', function() {
      it('should call getGeneproductObject successfully', function(done) {
        //uncomment below and update the code to test getGeneproductObject
        //instance.getGeneproductObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGenericAssociations', function() {
      it('should call getGenericAssociations successfully', function(done) {
        //uncomment below and update the code to test getGenericAssociations
        //instance.getGenericAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGenericObject', function() {
      it('should call getGenericObject successfully', function(done) {
        //uncomment below and update the code to test getGenericObject
        //instance.getGenericObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGenotypeDiseaseAssociations', function() {
      it('should call getGenotypeDiseaseAssociations successfully', function(done) {
        //uncomment below and update the code to test getGenotypeDiseaseAssociations
        //instance.getGenotypeDiseaseAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGenotypeGeneAssociations', function() {
      it('should call getGenotypeGeneAssociations successfully', function(done) {
        //uncomment below and update the code to test getGenotypeGeneAssociations
        //instance.getGenotypeGeneAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGenotypeGenotypeAssociations', function() {
      it('should call getGenotypeGenotypeAssociations successfully', function(done) {
        //uncomment below and update the code to test getGenotypeGenotypeAssociations
        //instance.getGenotypeGenotypeAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGenotypeObject', function() {
      it('should call getGenotypeObject successfully', function(done) {
        //uncomment below and update the code to test getGenotypeObject
        //instance.getGenotypeObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGenotypePhenotypeAssociations', function() {
      it('should call getGenotypePhenotypeAssociations successfully', function(done) {
        //uncomment below and update the code to test getGenotypePhenotypeAssociations
        //instance.getGenotypePhenotypeAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGotermGeneAssociations', function() {
      it('should call getGotermGeneAssociations successfully', function(done) {
        //uncomment below and update the code to test getGotermGeneAssociations
        //instance.getGotermGeneAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGotermObject', function() {
      it('should call getGotermObject successfully', function(done) {
        //uncomment below and update the code to test getGotermObject
        //instance.getGotermObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGotermPhenotypeAssociations', function() {
      it('should call getGotermPhenotypeAssociations successfully', function(done) {
        //uncomment below and update the code to test getGotermPhenotypeAssociations
        //instance.getGotermPhenotypeAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLiteratureDiseaseAssociations', function() {
      it('should call getLiteratureDiseaseAssociations successfully', function(done) {
        //uncomment below and update the code to test getLiteratureDiseaseAssociations
        //instance.getLiteratureDiseaseAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLiteratureGeneAssociations', function() {
      it('should call getLiteratureGeneAssociations successfully', function(done) {
        //uncomment below and update the code to test getLiteratureGeneAssociations
        //instance.getLiteratureGeneAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLiteratureGenotypeAssociations', function() {
      it('should call getLiteratureGenotypeAssociations successfully', function(done) {
        //uncomment below and update the code to test getLiteratureGenotypeAssociations
        //instance.getLiteratureGenotypeAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getParentObject', function() {
      it('should call getParentObject successfully', function(done) {
        //uncomment below and update the code to test getParentObject
        //instance.getParentObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getParentObject_0', function() {
      it('should call getParentObject_0 successfully', function(done) {
        //uncomment below and update the code to test getParentObject_0
        //instance.getParentObject_0(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPathwayGeneAssociations', function() {
      it('should call getPathwayGeneAssociations successfully', function(done) {
        //uncomment below and update the code to test getPathwayGeneAssociations
        //instance.getPathwayGeneAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPathwayObject', function() {
      it('should call getPathwayObject successfully', function(done) {
        //uncomment below and update the code to test getPathwayObject
        //instance.getPathwayObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPathwayParticipantAssociations', function() {
      it('should call getPathwayParticipantAssociations successfully', function(done) {
        //uncomment below and update the code to test getPathwayParticipantAssociations
        //instance.getPathwayParticipantAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPhenotypeAnatomyAssociations', function() {
      it('should call getPhenotypeAnatomyAssociations successfully', function(done) {
        //uncomment below and update the code to test getPhenotypeAnatomyAssociations
        //instance.getPhenotypeAnatomyAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPhenotypeFunctionAssociations', function() {
      it('should call getPhenotypeFunctionAssociations successfully', function(done) {
        //uncomment below and update the code to test getPhenotypeFunctionAssociations
        //instance.getPhenotypeFunctionAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPhenotypeGeneAssociations', function() {
      it('should call getPhenotypeGeneAssociations successfully', function(done) {
        //uncomment below and update the code to test getPhenotypeGeneAssociations
        //instance.getPhenotypeGeneAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPhenotypeGeneAssociations_0', function() {
      it('should call getPhenotypeGeneAssociations_0 successfully', function(done) {
        //uncomment below and update the code to test getPhenotypeGeneAssociations_0
        //instance.getPhenotypeGeneAssociations_0(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPhenotypeObject', function() {
      it('should call getPhenotypeObject successfully', function(done) {
        //uncomment below and update the code to test getPhenotypeObject
        //instance.getPhenotypeObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPhenotypePhenotypeAssociations', function() {
      it('should call getPhenotypePhenotypeAssociations successfully', function(done) {
        //uncomment below and update the code to test getPhenotypePhenotypeAssociations
        //instance.getPhenotypePhenotypeAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPubObject', function() {
      it('should call getPubObject successfully', function(done) {
        //uncomment below and update the code to test getPubObject
        //instance.getPubObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSequenceFeatureObject', function() {
      it('should call getSequenceFeatureObject successfully', function(done) {
        //uncomment below and update the code to test getSequenceFeatureObject
        //instance.getSequenceFeatureObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSubstanceExposures', function() {
      it('should call getSubstanceExposures successfully', function(done) {
        //uncomment below and update the code to test getSubstanceExposures
        //instance.getSubstanceExposures(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSubstanceInteractions', function() {
      it('should call getSubstanceInteractions successfully', function(done) {
        //uncomment below and update the code to test getSubstanceInteractions
        //instance.getSubstanceInteractions(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSubstanceObject', function() {
      it('should call getSubstanceObject successfully', function(done) {
        //uncomment below and update the code to test getSubstanceObject
        //instance.getSubstanceObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSubstanceParticipantInAssociations', function() {
      it('should call getSubstanceParticipantInAssociations successfully', function(done) {
        //uncomment below and update the code to test getSubstanceParticipantInAssociations
        //instance.getSubstanceParticipantInAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSubstanceRelationships', function() {
      it('should call getSubstanceRelationships successfully', function(done) {
        //uncomment below and update the code to test getSubstanceRelationships
        //instance.getSubstanceRelationships(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSubstanceRoleAssociations', function() {
      it('should call getSubstanceRoleAssociations successfully', function(done) {
        //uncomment below and update the code to test getSubstanceRoleAssociations
        //instance.getSubstanceRoleAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSubstanceTargetAssociations', function() {
      it('should call getSubstanceTargetAssociations successfully', function(done) {
        //uncomment below and update the code to test getSubstanceTargetAssociations
        //instance.getSubstanceTargetAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVariantGeneAssociations', function() {
      it('should call getVariantGeneAssociations successfully', function(done) {
        //uncomment below and update the code to test getVariantGeneAssociations
        //instance.getVariantGeneAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVariantGenotypeAssociations', function() {
      it('should call getVariantGenotypeAssociations successfully', function(done) {
        //uncomment below and update the code to test getVariantGenotypeAssociations
        //instance.getVariantGenotypeAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVariantObject', function() {
      it('should call getVariantObject successfully', function(done) {
        //uncomment below and update the code to test getVariantObject
        //instance.getVariantObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVariantPhenotypeAssociations', function() {
      it('should call getVariantPhenotypeAssociations successfully', function(done) {
        //uncomment below and update the code to test getVariantPhenotypeAssociations
        //instance.getVariantPhenotypeAssociations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
