/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BioLinkApi);
  }
}(this, function(expect, BioLinkApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BioLinkApi.CamApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CamApi', function() {
    describe('getActivityCollection', function() {
      it('should call getActivityCollection successfully', function(done) {
        //uncomment below and update the code to test getActivityCollection
        //instance.getActivityCollection(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getInstance', function() {
      it('should call getInstance successfully', function(done) {
        //uncomment below and update the code to test getInstance
        //instance.getInstance(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getModel', function() {
      it('should call getModel successfully', function(done) {
        //uncomment below and update the code to test getModel
        //instance.getModel(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getModelCollection', function() {
      it('should call getModelCollection successfully', function(done) {
        //uncomment below and update the code to test getModelCollection
        //instance.getModelCollection(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getModelCollection_0', function() {
      it('should call getModelCollection_0 successfully', function(done) {
        //uncomment below and update the code to test getModelCollection_0
        //instance.getModelCollection_0(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getModelCollection_1', function() {
      it('should call getModelCollection_1 successfully', function(done) {
        //uncomment below and update the code to test getModelCollection_1
        //instance.getModelCollection_1(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getModelCollection_2', function() {
      it('should call getModelCollection_2 successfully', function(done) {
        //uncomment below and update the code to test getModelCollection_2
        //instance.getModelCollection_2(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getModelContibutors', function() {
      it('should call getModelContibutors successfully', function(done) {
        //uncomment below and update the code to test getModelContibutors
        //instance.getModelContibutors(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getModelContibutors_0', function() {
      it('should call getModelContibutors_0 successfully', function(done) {
        //uncomment below and update the code to test getModelContibutors_0
        //instance.getModelContibutors_0(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPhysicalInteraction', function() {
      it('should call getPhysicalInteraction successfully', function(done) {
        //uncomment below and update the code to test getPhysicalInteraction
        //instance.getPhysicalInteraction(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
